---
# @version		tasks/main.yml 2016-05-13 15:24:00 UTC
# @package		gibilogic.perfect-component
# @description	Unzip sample component

- name: Create destination folder
  file: path=/var/www/joomla/tmp/sample-component state=directory

- name: Unzip component
  unarchive: src=sample-component.zip dest=/var/www/joomla/tmp/sample-component owner=vagrant group=www-data creates=/var/www/joomla/tmp/helloworld.xml

- name: Copy deploy file
  copy: src=deploy.sh dest=/usr/local/bin/deploy.sh mode=0755
